---
- name: Konfigurera alla servrar
  hosts: all
  become: yes
  roles:
    - common

- name: Konfigurera webserver
  hosts: webservers
  become: yes
  roles:
    - webserver

- name: Konfigurera database
  hosts: databases
  become: yes
  roles:
    - database

- name: Konfigurera client
  hosts: clients
  become: yes
  roles:
    - client
